### ISSUE TITLE
Is this active / maintained still? 

### ISSUE THREAD

**Issue by cpanato** [sigstore/rekor-operator#130]
What's the status of this repo, if not maintained we can place into archive?

I personally not working on this anymore, but also we did not get much traction.
Maybe we can archive and in the future if have interest we can push it back

@sigstore/core-team

**Comment by cpanato** [comment]
@lukehinds lets archive this? do we need to include this in the TSC meeting?

cc @bobcallaway @priyawadhwa @SantiagoTorres @trevrosen

**Comment by bobcallaway** [comment]
yes, i'll put this as an agenda item for the next TSC meeting

**Comment by cpanato** [comment]
the decision was to archive this project for now.
doing that
