### ISSUE TITLE
What this project current status?

### ISSUE THREAD

**Issue by zchee** [sigstore/rekor-operator#52]
**Question**
What this project current status?

Currently, this repository seems to have kubebuilder initialize code only.
If no maintainer for now, I want to develop rekor-operator.
I know how to use the controller-runtime and have developed several operators in-house.
If any sigstore developers planned to start developing this in the future, I will contribute to it.

What do you think?

**Comment by zchee** [comment]
cc: @dlorenc

**Comment by dlorenc** [comment]
I think @font had some ideas here but it seems stale. If you'd like to try go for it!

**Comment by zchee** [comment]
@dlorenc Okay, so forked and develop, then send PR (but might be huge diff)

**Comment by cpanato** [comment]
@zchee that sounds good, i will wait for your PR, I was doing some things here, but did not push yet, because I need a bit more time. but go ahead and we move forward after your PR

**Comment by zchee** [comment]
@cpanato Thanks! and I'm interesting in your local code (_not push yet_)  👀 
It will give me an idea of what architecture you were thinking of, which could be helpful in the early stages of my development.
Could you push it somewhere? (Yes, incomplete implementation is fine

**Comment by cpanato** [comment]
to be honest i dont have much things, the code I have is a dirty and will need some refactor and add things to be more useful, was doing more to understand this.

i will refactor things more in the xmas time that I will have a bit more time :)

**Comment by zchee** [comment]
I'll starting develop based on #60. Close.
